class ResponseMessage():
    USER_ALREADY_EXIST = "User already Exist"
    USER_NOT_FOUND = "User not Found"
    PASSWORD_SET_ALREADY = "Password already Set"
    PASSWORD_NOT_MATCH = "Password Does not Match"
    MOBILE_NUMBER_ALREADY_SET = "Mobile Number Already Set"
    INVALID_OTP = "Invalid OTP please entec correct otp"
    TOKEN_EMPTY = "No Token to verify"
    INVALID_TOKEN = "Token is invalid"
    OTP_COUNT_REACHED = "Otp count has reached please try after 30 mins"
    OTP_EXPIRED = "Otp has been expired"
    OTP_NOT_CREATED = "OTP not created yet!"